version: "3.7"
services:

  nginx:
    image: nginx:latest
    volumes:
      - ./ops/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "4000:4000"

  api:
    build:
      dockerfile: ./ops/dockerfile/api.Dockerfile
      context: .
#    command: "./bin/api"
    environment:
      - KAFKA_BROKERS=kafka:9092
    ports:
      - "8081"
    depends_on:
      - kafka
      - redis
    volumes:
      - .:/app

  process:
    build:
      dockerfile: ./ops/dockerfile/process.Dockerfile
      context: .
#    command: "./bin/process"
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
      - redis
    volumes:
      - .:/app

  kafka:
    image: docker.io/bitnami/kafka:2-debian-10
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    healthcheck:
      test:
        ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 30s
      timeout: 10s
      retries: 4

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

  zookeeper:
    image: docker.io/bitnami/zookeeper:3-debian-10
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
