version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    container_name: backend_2_app
    environment:
      REDIS_URL: "redis:6379"
    ports:
      - '3000:3000'
    volumes:
      - .:/app

  redis:
    image: "redis:alpine3.14"
    container_name: backend_2_redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  redis:
